set fenc=utf-8
set term=builtin_ansi
set nocompatible
set noswapfile
set showcmd
set viminfo+=n$ZDOTDIR/.vim/.viminfo

set number
set showmatch
set laststatus=2

set list
set listchars=tab:>-,trail:.,eol:↵
set expandtab
set tabstop=2
set shiftwidth=2
set autoindent

syntax on
set background=dark
colorscheme hybrid
set t_Co=256

set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch
